language: minimal
os: linux
services:
- docker
cache:
  bundler: true
  directories:
    - $HOME/docker

before_install:
- if [[ -e $HOME/docker/stahl_bootstrap-builder.tgz ]]; then zcat $HOME/docker/stahl_bootstrap-builder.tgz | docker load; fi
- docker build -t remexre/stahl_bootstrap-builder .travis

script: docker run -v "$PWD:/code" --rm remexre/stahl_bootstrap-builder make ci

before_cache:
- mkdir -p $HOME/docker
- docker save remexre/stahl_bootstrap-builder $(docker history -q remexre/stahl_bootstrap-builder | grep -v missing) | gzip > $HOME/docker/stahl_bootstrap-builder.tgz

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file: out/stahl_bootstrap
  on:
    tags: true
  skip_cleanup: true
